import type { User, Post } from '../types/index.js';

/**
 * Mock user database
 * In production, this would be fetched from a real database/API
 */
export const users: User[] = [
  {
    id: 'user-1',
    name: 'Alex Johnson',
    title: 'Product Designer at TechCorp',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    connections: 500,
    isCurrentUser: true,
    location: 'San Francisco, CA',
    about:
      'Passionate Product Designer with 5+ years of experience in creating user-centric digital experiences. I specialize in design systems, mobile-first strategies, and bridging the gap between design and engineering.',
    email: 'alex.j@design.com',
    experience: [
      {
        id: 'exp-1',
        title: 'Product Designer',
        company: 'TechCorp',
        employmentType: 'Full-time',
        startDate: 'Jan 2021',
        endDate: 'Present',
        duration: '3 yrs 5 mos',
        location: 'San Francisco, California',
        logo: 'https://api.dicebear.com/7.x/initials/svg?seed=TC',
      },
      {
        id: 'exp-2',
        title: 'UX Designer',
        company: 'Designly',
        employmentType: 'Full-time',
        startDate: 'Aug 2018',
        endDate: 'Dec 2020',
        duration: '2 yrs 5 mos',
        location: 'Remote',
        logo: 'https://api.dicebear.com/7.x/initials/svg?seed=DG',
      },
    ],
    skills: ['UI/UX Design', 'Design Systems', 'Figma', 'Prototyping', 'User Research', 'Mobile Design'],
  },
  {
    id: 'user-2',
    name: 'Sarah Miller',
    title: 'UX Manager at Designly',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    connections: 753,
    isCurrentUser: false,
    isOnline: true,
    lastSeen: 'Active now',
  },
  {
    id: 'user-3',
    name: 'Jordan Lee',
    title: 'Lead Dev at Webflow',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan',
    connections: 621,
    isCurrentUser: false,
    isOnline: false,
    lastSeen: '1h ago',
  },
  {
    id: 'user-4',
    name: 'Michael Chen',
    title: 'CTO at TechFlow',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    connections: 1842,
    isCurrentUser: false,
    isOnline: false,
    lastSeen: 'Yesterday',
  },
  {
    id: 'user-5',
    name: 'Emily Roberts',
    title: 'Frontend Engineer at Stripe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    connections: 934,
    isCurrentUser: false,
    isOnline: false,
    lastSeen: '2d ago',
  },
  {
    id: 'user-6',
    name: 'David Kim',
    title: 'Product Manager at Google',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    connections: 2156,
    isCurrentUser: false,
    isOnline: false,
    lastSeen: '2h ago',
  },
  {
    id: 'user-7',
    name: 'Sarah Miller',
    title: 'Senior Recruiter at TechCorp',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SarahM',
    connections: 1240,
    isCurrentUser: false,
    isOnline: true,
    lastSeen: 'Active now',
  },
  {
    id: 'user-8',
    name: 'Marcus Thompson',
    title: 'Software Architect at Amazon',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    connections: 1876,
    isCurrentUser: false,
    isOnline: false,
    lastSeen: '3h ago',
  },
  {
    id: 'user-9',
    name: 'Lisa Chen',
    title: 'Data Scientist at Meta',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
    connections: 1456,
    isCurrentUser: false,
    isOnline: true,
    lastSeen: 'Active now',
  },
  {
    id: 'user-10',
    name: 'James Rodriguez',
    title: 'Full Stack Developer at Spotify',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    connections: 892,
    isCurrentUser: false,
    isOnline: false,
    lastSeen: '1d ago',
  },
  {
    id: 'user-11',
    name: 'Nina Patel',
    title: 'Head of Design at Notion',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nina',
    connections: 2341,
    isCurrentUser: false,
    isOnline: false,
    lastSeen: '4h ago',
  },
  {
    id: 'user-12',
    name: 'Carlos Mendoza',
    title: 'DevOps Engineer at Netflix',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
    connections: 1123,
    isCurrentUser: false,
    isOnline: false,
    lastSeen: '2d ago',
  },
  {
    id: 'user-13',
    name: 'Amanda Brooks',
    title: 'UX Researcher at Adobe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amanda',
    connections: 756,
    isCurrentUser: false,
    isOnline: true,
    lastSeen: 'Active now',
  },
  {
    id: 'user-14',
    name: 'Ryan Foster',
    title: 'Mobile Developer at Uber',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ryan',
    connections: 634,
    isCurrentUser: false,
    isOnline: false,
    lastSeen: '5h ago',
  },
  {
    id: 'user-15',
    name: 'Sophie Anderson',
    title: 'Tech Lead at Shopify',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie',
    connections: 1987,
    isCurrentUser: false,
    isOnline: false,
    lastSeen: '6h ago',
  },
];

/**
 * Mock posts database
 * In production, this would be fetched from a real database/API
 */
export const posts: Post[] = [
  {
    id: 'post-1',
    userId: 'user-2',
    content:
      "Excited to share my latest project on minimalist interfaces. We focused on reducing cognitive load while maintaining functionality. What's your take on minimal UI? 🚀",
    timestamp: '2h',
    likes: 124,
    comments: 18,
    image: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=600&h=400&fit=crop',
  },
  {
    id: 'post-2',
    userId: 'user-4',
    content:
      "Always proud of the team at TechFlow. We just hit a major milestone in our backend scalability project! Grateful for everyone's hard work.",
    timestamp: '5h',
    likes: 89,
    comments: 4,
    image: null,
  },
  {
    id: 'post-3',
    userId: 'user-5',
    content:
      'Just published a new article about React Server Components and their impact on modern web architecture. Link in comments! 📝',
    timestamp: '1d',
    likes: 267,
    comments: 32,
    image: null,
  },
  {
    id: 'post-4',
    userId: 'user-6',
    content:
      "Hiring! We're looking for a Senior Product Designer to join our team. Remote-friendly, competitive salary, and amazing benefits. DM me if interested! 💼",
    timestamp: '2d',
    likes: 421,
    comments: 56,
    image: null,
  },
  {
    id: 'post-5',
    userId: 'user-8',
    content:
      'After 10 years in software architecture, I can confidently say that simplicity beats complexity every single time. Build systems that humans can understand and maintain.',
    timestamp: '3h',
    likes: 312,
    comments: 45,
    image: null,
  },
  {
    id: 'post-6',
    userId: 'user-9',
    content:
      'Data science tip: Clean data is more valuable than complex algorithms. Spent the last month refining our data pipeline and the results speak for themselves. 📊',
    timestamp: '6h',
    likes: 189,
    comments: 23,
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop',
  },
  {
    id: 'post-7',
    userId: 'user-10',
    content:
      'Excited to announce that I just open-sourced my side project! A lightweight TypeScript library for building accessible components. Check it out on GitHub! 🎉',
    timestamp: '8h',
    likes: 456,
    comments: 67,
    image: null,
  },
  {
    id: 'post-8',
    userId: 'user-11',
    content:
      'Design systems are not just component libraries. They are the language that connects product, design, and engineering. Here is how we approach it at Notion...',
    timestamp: '12h',
    likes: 534,
    comments: 89,
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&h=400&fit=crop',
  },
  {
    id: 'post-9',
    userId: 'user-12',
    content:
      'Kubernetes in production: lessons learned after managing 200+ microservices. Thread incoming 🧵',
    timestamp: '1d',
    likes: 721,
    comments: 134,
    image: null,
  },
  {
    id: 'post-10',
    userId: 'user-13',
    content:
      'User research is not about validating your ideas. It is about discovering what you do not know. Stop asking users what they want and start observing what they actually do.',
    timestamp: '1d',
    likes: 298,
    comments: 41,
    image: null,
  },
  {
    id: 'post-11',
    userId: 'user-14',
    content:
      'Flutter vs React Native in 2024? I have built production apps with both. Here is my honest comparison and when to choose each...',
    timestamp: '2d',
    likes: 892,
    comments: 156,
    image: null,
  },
  {
    id: 'post-12',
    userId: 'user-15',
    content:
      'Leading a team of 15 engineers taught me that technical skills are just the baseline. Communication, empathy, and clear vision matter more than you think.',
    timestamp: '2d',
    likes: 623,
    comments: 78,
    image: null,
  },
  {
    id: 'post-13',
    userId: 'user-3',
    content:
      'Just wrapped up a challenging sprint at Webflow. Shipped a major performance optimization that reduced load times by 40%. Proud of the team! 🚀',
    timestamp: '3d',
    likes: 167,
    comments: 19,
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop',
  },
  {
    id: 'post-14',
    userId: 'user-9',
    content:
      'Machine learning does not solve business problems. Understanding your data and asking the right questions does. ML is just a tool in the toolbox.',
    timestamp: '3d',
    likes: 445,
    comments: 52,
    image: null,
  },
  {
    id: 'post-15',
    userId: 'user-11',
    content:
      'Hot take: Your design portfolio should show your process, not just pretty pictures. Employers want to see how you think and solve problems.',
    timestamp: '4d',
    likes: 756,
    comments: 91,
    image: null,
  },
];
