import type { Job } from '@/types/index.js';

/**
 * Mock Jobs Database
 * In a real application, this would come from a backend API
 */

export const jobs: Job[] = [
  {
    id: 'job-1',
    title: 'Senior UI Designer',
    company: {
      id: 'company-1',
      name: 'DesignStudio Co.',
      logo: 'https://api.dicebear.com/7.x/initials/svg?seed=DS&backgroundColor=2d5016',
      size: '51-200 employees',
      industry: 'IT Services',
      description: 'DesignStudio is a global creative agency and product lab. We believe in the power of design to solve complex business problems and create meaningful human experiences. Our team is remote-first and highly collaborative.',
    },
    location: {
      city: 'San Francisco',
      state: 'CA',
      country: 'USA',
      isRemote: true,
    },
    type: 'Full-time',
    experienceLevel: 'Mid-Senior level',
    description: 'We are looking for a creative and detail-oriented Senior UI Designer to join our core product team. You will be responsible for creating beautiful, intuitive, and functional user interfaces across our mobile and web platforms.',
    responsibilities: [
      'Create high-fidelity wireframes and interactive prototypes',
      'Collaborate with cross-functional engineering and product teams',
      'Maintain and evolve the global design system',
      'Conduct user research and usability testing to inform UI decisions',
    ],
    requirements: [
      '5+ years of experience in product design or UI design roles',
      'Expert proficiency in Figma, Protopie, and Adobe Creative Suite',
      'Strong portfolio showcasing shipped mobile application designs',
      'Experience working in an Agile/Scrum environment',
      'Excellent communication and presentation skills',
    ],
    postedDate: '2 hours ago',
    applicants: 15,
    isActivelyHiring: true,
  },
  {
    id: 'job-2',
    title: 'Product Manager',
    company: {
      id: 'company-2',
      name: 'GlobalLink',
      logo: 'https://api.dicebear.com/7.x/initials/svg?seed=GL&backgroundColor=f0a830',
      size: '1001-5000 employees',
      industry: 'Technology',
      description: 'GlobalLink connects businesses worldwide through innovative technology solutions. We are committed to building products that empower teams to collaborate effectively across borders.',
    },
    location: {
      city: 'New York',
      state: 'NY',
      country: 'USA',
      isRemote: false,
    },
    type: 'Full-time',
    experienceLevel: 'Mid-Senior level',
    description: 'We are seeking an experienced Product Manager to lead our core platform initiatives. You will work closely with engineering, design, and business stakeholders to define and deliver product features that delight our customers.',
    responsibilities: [
      'Define product vision and roadmap for key platform features',
      'Gather and prioritize product requirements from stakeholders',
      'Work with engineering teams to deliver features on time',
      'Analyze product metrics and user feedback to drive improvements',
      'Present product updates to executive leadership',
    ],
    requirements: [
      '4+ years of product management experience in B2B SaaS',
      'Strong analytical and problem-solving skills',
      'Experience with agile development methodologies',
      'Excellent written and verbal communication skills',
      'Technical background or CS degree preferred',
    ],
    postedDate: '5 hours ago',
    applicants: 42,
  },
  {
    id: 'job-3',
    title: 'Frontend Engineer',
    company: {
      id: 'company-3',
      name: 'TechCore Systems',
      logo: 'https://api.dicebear.com/7.x/initials/svg?seed=TC&backgroundColor=34d399',
      size: '201-500 employees',
      industry: 'Software Development',
      description: 'TechCore Systems builds enterprise-grade software solutions for Fortune 500 companies. We value innovation, technical excellence, and a collaborative work environment.',
    },
    location: {
      city: 'Austin',
      state: 'TX',
      country: 'USA',
      isRemote: false,
    },
    type: 'Full-time',
    experienceLevel: 'Mid-Senior level',
    salary: {
      min: 120000,
      max: 160000,
      currency: 'USD',
    },
    description: 'Join our frontend team to build modern, performant web applications using React, TypeScript, and Next.js. You will work on challenging problems and have the opportunity to influence our technical direction.',
    responsibilities: [
      'Build responsive, accessible web applications',
      'Collaborate with designers and backend engineers',
      'Write clean, maintainable, and well-tested code',
      'Participate in code reviews and technical discussions',
      'Mentor junior engineers and contribute to team culture',
    ],
    requirements: [
      '5+ years of professional frontend development experience',
      'Expert knowledge of React, TypeScript, and modern CSS',
      'Experience with Next.js or similar frameworks',
      'Strong understanding of web performance optimization',
      'Excellent debugging and problem-solving skills',
    ],
    postedDate: '1 day ago',
    applicants: 87,
  },
  {
    id: 'job-4',
    title: 'Staff UX Researcher',
    company: {
      id: 'company-4',
      name: 'Social Net',
      logo: 'https://api.dicebear.com/7.x/initials/svg?seed=SN&backgroundColor=c084fc',
      size: '10001+ employees',
      industry: 'Social Media',
      description: 'Social Net is a leading social media platform connecting millions of users worldwide. We are dedicated to building safe, engaging, and meaningful online communities.',
    },
    location: {
      city: 'Seattle',
      state: 'WA',
      country: 'USA',
      isRemote: true,
    },
    type: 'Full-time',
    experienceLevel: 'Mid-Senior level',
    description: 'We are looking for a Staff UX Researcher to lead research initiatives across our core products. You will work with product, design, and engineering teams to uncover user insights that drive product strategy.',
    responsibilities: [
      'Design and execute qualitative and quantitative research studies',
      'Synthesize research findings into actionable insights',
      'Present research findings to cross-functional stakeholders',
      'Build and maintain research repositories and tools',
      'Mentor other researchers and promote research best practices',
    ],
    requirements: [
      '8+ years of experience in UX research or related field',
      'Expertise in both qualitative and quantitative research methods',
      'Experience working on consumer-facing products at scale',
      'Strong data analysis and storytelling skills',
      'PhD in HCI, Psychology, or related field preferred',
    ],
    postedDate: '2 days ago',
    applicants: 34,
    tags: ['Remote'],
  },
  {
    id: 'job-5',
    title: 'Data Scientist',
    company: {
      id: 'company-5',
      name: 'Analytics Pro',
      logo: 'https://api.dicebear.com/7.x/initials/svg?seed=AP&backgroundColor=3b82f6',
      size: '501-1000 employees',
      industry: 'Data Analytics',
      description: 'Analytics Pro provides cutting-edge data analytics solutions to enterprises. We help companies turn their data into actionable insights using machine learning and advanced analytics.',
    },
    location: {
      city: 'Boston',
      state: 'MA',
      country: 'USA',
      isRemote: true,
    },
    type: 'Full-time',
    experienceLevel: 'Entry level',
    salary: {
      min: 90000,
      max: 120000,
      currency: 'USD',
    },
    description: 'Join our data science team to build predictive models and analytics solutions for our enterprise clients. This is a great opportunity for recent graduates or early-career data scientists.',
    responsibilities: [
      'Develop and deploy machine learning models',
      'Analyze large datasets to extract meaningful insights',
      'Collaborate with engineering teams to productionize models',
      'Create data visualizations and dashboards',
      'Document methodologies and present findings to clients',
    ],
    requirements: [
      '1-2 years of experience in data science or analytics',
      'Strong programming skills in Python and SQL',
      'Experience with scikit-learn, pandas, and numpy',
      'Understanding of statistical analysis and A/B testing',
      'Bachelor\'s or Master\'s degree in Computer Science, Statistics, or related field',
    ],
    postedDate: '3 days ago',
    applicants: 156,
    tags: ['Remote', 'Entry Level'],
  },
  {
    id: 'job-6',
    title: 'Marketing Manager',
    company: {
      id: 'company-6',
      name: 'GrowthHub',
      logo: 'https://api.dicebear.com/7.x/initials/svg?seed=GH&backgroundColor=ef4444',
      size: '51-200 employees',
      industry: 'Marketing & Advertising',
      description: 'GrowthHub is a digital marketing agency specializing in growth marketing for SaaS companies. We combine data-driven strategies with creative campaigns to drive customer acquisition and retention.',
    },
    location: {
      city: 'Los Angeles',
      state: 'CA',
      country: 'USA',
      isRemote: false,
    },
    type: 'Full-time',
    experienceLevel: 'Mid-Senior level',
    description: 'We are seeking a Marketing Manager to lead our client campaigns and internal marketing initiatives. You will work with a team of creatives and analysts to deliver measurable results.',
    responsibilities: [
      'Develop and execute marketing strategies for client accounts',
      'Manage marketing budgets and campaign performance',
      'Collaborate with creative teams on campaign assets',
      'Analyze marketing data and optimize campaigns',
      'Build relationships with clients and stakeholders',
    ],
    requirements: [
      '5+ years of marketing experience, preferably in B2B SaaS',
      'Proven track record of running successful marketing campaigns',
      'Experience with marketing automation tools (HubSpot, Marketo)',
      'Strong analytical and project management skills',
      'Excellent written and verbal communication',
    ],
    postedDate: '4 days ago',
    applicants: 63,
  },
  {
    id: 'job-7',
    title: 'DevOps Engineer',
    company: {
      id: 'company-7',
      name: 'CloudScale',
      logo: 'https://api.dicebear.com/7.x/initials/svg?seed=CS&backgroundColor=8b5cf6',
      size: '201-500 employees',
      industry: 'Cloud Infrastructure',
      description: 'CloudScale provides cloud infrastructure and DevOps services to help companies scale their applications reliably. We work with cutting-edge cloud technologies and automation tools.',
    },
    location: {
      city: 'Denver',
      state: 'CO',
      country: 'USA',
      isRemote: true,
    },
    type: 'Full-time',
    experienceLevel: 'Mid-Senior level',
    salary: {
      min: 130000,
      max: 170000,
      currency: 'USD',
    },
    description: 'We are looking for a DevOps Engineer to help us build and maintain scalable cloud infrastructure. You will work with Kubernetes, Terraform, and AWS to ensure our systems are reliable and performant.',
    responsibilities: [
      'Design and implement CI/CD pipelines',
      'Manage and optimize cloud infrastructure (AWS, GCP)',
      'Automate deployment and scaling processes',
      'Monitor system performance and troubleshoot issues',
      'Implement security best practices and compliance requirements',
    ],
    requirements: [
      '4+ years of experience in DevOps or Site Reliability Engineering',
      'Strong experience with Kubernetes and Docker',
      'Proficiency in infrastructure as code (Terraform, CloudFormation)',
      'Experience with monitoring tools (Prometheus, Grafana, DataDog)',
      'Solid understanding of networking and security principles',
    ],
    postedDate: '1 week ago',
    applicants: 92,
    isActivelyHiring: true,
    tags: ['Remote'],
  },
  {
    id: 'job-8',
    title: 'Sales Development Representative',
    company: {
      id: 'company-8',
      name: 'SalesPro Inc',
      logo: 'https://api.dicebear.com/7.x/initials/svg?seed=SP&backgroundColor=f59e0b',
      size: '51-200 employees',
      industry: 'Sales Software',
      description: 'SalesPro Inc builds sales enablement tools that help sales teams close more deals. We are a fast-growing startup with a mission to revolutionize B2B sales.',
    },
    location: {
      city: 'Chicago',
      state: 'IL',
      country: 'USA',
      isRemote: false,
    },
    type: 'Full-time',
    experienceLevel: 'Entry level',
    description: 'Join our sales team as a Sales Development Representative. This is an entry-level role with significant growth potential. You will be responsible for generating new business opportunities.',
    responsibilities: [
      'Prospect and qualify leads through cold calling and email',
      'Schedule meetings for Account Executives',
      'Maintain accurate records in CRM (Salesforce)',
      'Collaborate with marketing on lead generation campaigns',
      'Meet or exceed monthly quota targets',
    ],
    requirements: [
      '0-2 years of sales or customer-facing experience',
      'Excellent communication and interpersonal skills',
      'Self-motivated and goal-oriented',
      'Comfortable with cold calling and rejection',
      'Bachelor\'s degree preferred but not required',
    ],
    postedDate: '5 days ago',
    applicants: 234,
    tags: ['Entry Level'],
  },
];
