import type { Notification, User } from '@/types/index.js';

/**
 * Mock Notifications Database
 * In a real application, this would come from a backend API
 */

export const notifications: Notification[] = [
  {
    id: 'notif-1',
    type: 'profile_view',
    userId: 'user-16',
    user: {
      id: 'user-16',
      name: 'John Doe',
      title: 'Software Engineer at Google',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=JohnDoe',
      connections: 432,
      isCurrentUser: false,
    },
    message: 'viewed your profile',
    timestamp: '2h',
    isRead: false,
  },
  {
    id: 'notif-2',
    type: 'post_like',
    userId: 'user-17',
    user: {
      id: 'user-17',
      name: 'Sarah Smith',
      title: 'Product Manager at Microsoft',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SarahSmith',
      connections: 678,
      isCurrentUser: false,
    },
    message: 'and 5 others liked your post:',
    postTitle: 'The future of UI design',
    timestamp: '4h',
    isRead: true,
  },
  {
    id: 'notif-3',
    type: 'job_alert',
    message: 'New Job Alert: Senior Product Designer at TechCorp',
    jobTitle: 'Senior Product Designer',
    companyName: 'TechCorp',
    timestamp: '6h',
    isRead: true,
  },
  {
    id: 'notif-4',
    type: 'work_anniversary',
    userId: 'user-18',
    user: {
      id: 'user-18',
      name: 'Alex Johnson',
      title: 'Product Designer at Google',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AlexJ',
      connections: 1234,
      isCurrentUser: false,
    },
    message: "Celebrate Alex Johnson's 5th work anniversary at Google",
    timestamp: '8h',
    isRead: false,
    actionLabel: 'Say Congrats',
  },
  {
    id: 'notif-5',
    type: 'mention',
    userId: 'user-19',
    user: {
      id: 'user-19',
      name: 'Maya Chen',
      title: 'UX Designer at Airbnb',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maya',
      connections: 892,
      isCurrentUser: false,
    },
    message: 'mentioned you in a comment: "@DesignUser Great insights on the..."',
    timestamp: '1d',
    isRead: true,
  },
  {
    id: 'notif-6',
    type: 'profile_view',
    userId: 'user-20',
    user: {
      id: 'user-20',
      name: 'Robert Wilson',
      title: 'Tech Lead at Amazon',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
      connections: 1567,
      isCurrentUser: false,
    },
    message: 'viewed your profile',
    timestamp: '2d',
    isRead: true,
  },
  {
    id: 'notif-7',
    type: 'post_comment',
    userId: 'user-21',
    user: {
      id: 'user-21',
      name: 'Lisa Anderson',
      title: 'Product Designer at Spotify',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
      connections: 543,
      isCurrentUser: false,
    },
    message: 'commented on your post: "Design Systems Best Practices"',
    postTitle: 'Design Systems Best Practices',
    timestamp: '3d',
    isRead: true,
  },
  {
    id: 'notif-8',
    type: 'job_alert',
    message: 'New Job Alert: Frontend Engineer at Stripe',
    jobTitle: 'Frontend Engineer',
    companyName: 'Stripe',
    timestamp: '4d',
    isRead: true,
  },
];
